# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""Module to compute DeepMatching"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_deepmatching')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_deepmatching')
    _deepmatching = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_deepmatching', [dirname(__file__)])
        except ImportError:
            import _deepmatching
            return _deepmatching
        try:
            _mod = imp.load_module('_deepmatching', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _deepmatching = swig_import_helper()
    del swig_import_helper
else:
    import _deepmatching
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import builtins

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except builtins.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except builtins.Exception:
    class _object:
        pass
    _newclass = 0


def deepmatching_numpy(cim1, cim2, options):
    return _deepmatching.deepmatching_numpy(cim1, cim2, options)
deepmatching_numpy = _deepmatching.deepmatching_numpy

def usage_python():
    return _deepmatching.usage_python()
usage_python = _deepmatching.usage_python

from numpy import float32, rollaxis, ascontiguousarray
def deepmatching( im1=None, im2=None, options=""):
    """
    matches = deepmatching.deepmatching(image1, image2, options='')
    Compute the 'DeepMatching' between two images.
    Images must be HxWx3 numpy arrays (converted to float32).
    Options is an optional string argument ('' by default), to set the options.
    The function returns a numpy array with 6 columns, each row being x1 y1 x2 y2 score index.
     (index refers to the local maximum from which the match was retrieved)
    Version 1.2"""
    if im1 is None or im2 is None:
      usage_python()
      return

# convert images
    if im1.dtype != float32:
        im1 = im1.astype(float32)
    if im2.dtype != float32:
        im2 = im2.astype(float32)
    assert len(im1.shape)==3 and len(im2.shape)==3, "images must have 3 dimensions"
    h, w, nchannels = im1.shape
    assert nchannels==3, "images must have 3 channels"
    im1 = ascontiguousarray(rollaxis(im1,2))
    im2 = ascontiguousarray(rollaxis(im2,2))
    corres = deepmatching_numpy( im1, im2, options)
    return corres

# This file is compatible with both classic and new-style classes.